# Site settings
title: Anyone. Anywhere 
email: 
description: "nokia n-gage library"
url: "http://n-gage.site" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->
