# Site settings
title: Anyone. Anywhere 
email: 
description: "nokia n-gage library"
url: "http://n-gage.site" # the base hostname & protocol for your site
disqus: 'n-gage-2'

permalink: /:title/

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->

# Paginate
paginate: 10
